version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
